### ISSUE TITLE
Consider using zsh + oh-my-zsh as default shell?

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#137]
Might make the out-of-the-box scripting experience a bit nicer.

**Comment by blairdrummond** [comment]
I think zsh is much nicer than bash, it's now packaged as the default in MacOS (which is probably more prevalent in users than linux, whether I like it or not), and oh-my-zsh provides nice git support. Additionally, I do not see many drawbacks.

CC @brendangadd

**Comment by sylus** [comment]
Why are we removing this then? Zshell is what most developers are familiar with including myself, and assume most data scientists?

Can we keep this as is?

**Comment by sylus** [comment]
@zachomedia

**Comment by brendangadd** [comment]
To clarify the situation:
* The change in default shell came in as part of an unrelated architectural change – I missed it in review; that's my bad
* Changes like this need proactive discussion, so it's being reverted
* The PR that reverts this behaviour (#169) does not close this issue, which can remain open for (proactive) discussion
* `zsh` remains installed in the image, so users who want to use it still can

Actions I've taken:
* Moved #169 to Review status (LGTM. Can you take a look @ca-scribner?)
* Moved this issue out of this sprint as it is not a priority
* Asked @Colette-G to have UX gather some evidence about this so that objective discussion is possible

/cc @sylus @blairdrummond

**Comment by bryanpaget** [comment]
Or take it a step further with [Starship](https://starship.rs/).

**Comment by brendangadd** [comment]
@bryanpaget Starship looks cool, and compatible with Bash (default) and zsh (included in image). Maybe worth a separate issue if you feel it's a major UX boost.
