### ISSUE TITLE
Proposal: Start using semantic version tags in the manifest

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#214]
Let's start implementing semantic releases of this repo more diligently. In the kubeflow image drop-down, we'll list

- JupyterLab-CPU:v1.0.2
- JupyterLab-PyTorch:v1.0.2
- JupyterLab-Tensorflow:v1.0.2
- RStudio:v1.0.2
- JupyterLab-CPU:$edge
- JupyterLab-PyTorch:$edge
- JupyterLab-Tensorflow:$edge
- RStudio:$edge

Then Semantic Releases will come with a CHANGELOG entry. **Note: We'll probably need a description in the UI to explain the naming convention**

(I would propose that the CHANGELOG entries get registered as bilingual configmaps or something, to be included in the kubeflow home page, but will leave that as a separate issue)

CC @brendangadd @ca-scribner 

How does this sound for a start?

**Comment by ca-scribner** [comment]
I **love** versioning, and I **loath** human-driven versioning.  So depending on implementation this puts me in an awkward spot in my Venn Diagram :face_with_head_bandage: 

Completely agree that we need some sort of deterministic identity that makes more sense to users if we include more than one instance of an image in the dropdown.  It also is a nice reminder to users (hey look, dont you want all the new fun things that must be in these newer images???).

My complaint on semantic versioning is when humans are involved.  If there's a human that has to move the number, frequent releases in informal settings will cause mistakes (easy to forget, etc., which then means there's two v1.0.2's floating around etc..).  I love commit-versioned things because it is easy to automate.

I'm good with this if we set it up to be foolproof.  For example if at least the smallest number in the version is completely automatic and incremented on every push to master.  Not sure how best to automate that (how do you keep track of versioning inside the CI after it has already been committed?) but if there's a simple-ish way then I'm in.  Then humans can occasionally change any other parts of the version number based on releases or whatever.  
<--**edit:** Maybe we use PR number as the last number in the version?  So long as we merge via PRs, it'll be unique (v1.0.PR_NUM, or even just PR_NUM)

Would temporal versioning be a good compromise?  eg:
* JupyterLab-CPU:2020-02-11
* JupyterLab-CPU:2020-02-18 (<--or maybe JupyterLab-CPU:2020-02-18-preview)
Probably need something finer grained though.  Releasing two images in the same day means the second clobbers the first, and you might not mean to release the second.  Would probably have to version by the second, which is a real awkward tag

**Comment by blairdrummond** [comment]
I definitely feel your pain re-automation, but I think we have an obligation (and the edge version will be rolling release). 

I think what's important is that every change in semantic version be accompanied by a human written description of what changed (and maybe why), and so I think it can't really be automated. It probably also has to be bilingual.

I suppose we could go with the approach `Every commit to master uses a long-form commit message. It must be user-friendly and bi-lingual.` but making every commit/merge to master bilingual makes that complicated too.

**Comment by ca-scribner** [comment]
I think a release note per semantic version change is out of our capacity
atm. Especially bilingual ones. You and I wouldn’t be able to commit for
example

**Comment by brendangadd** [comment]
Closing as stale. But @Jose-Matsuda will be looking into this as part of StatCan/daaas#961.
