### ISSUE TITLE
Add graphviz

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-containers#237]

**Comment by goatsweater** [comment]
My understanding is that part of the justification for graphviz is the integrations with other toolchains, especially when building documentation.

A bunch of people do use draw.io, but I think they are using the website interface then downloading the results. No reason they can't use it for integrations - I just haven't seen the demand yet. Having a local install would at least allow [rending when building documentation](https://pypi.org/project/sphinxcontrib-drawio/), even if generating the files is still manual.

Haven't seen requests for use of mermaid yet, but that could be due to lack of familiarity among users.

**Comment by chuckbelisle** [comment]
Graphviz was determined to be a OpenM++ dependency.

**Comment by KrisWilliamson** [comment]
Graphviz does not appear to be installed on the Jupyter-notebook image.

Can be installed in the docker-file by multiple ways.
Run apt-get graphviz
Run mamba install graphviz
etc.

**Comment by KrisWilliamson** [comment]
@chuckbelisle 
Blocked because of this message, not sure which issue it belongs to:

> [Wednesday 2:11 p.m.] Matsuda, Jose (he, him, his | il, le, lui) (StatCan)
> 
> I forgot to mention to Williamson, Kristian (StatCan) (and idk if Chuck or Souheil brought it up to you independently) that aaw-kubeflow-containers currently fails building, and as well Souheil is doing some cleanup of those dockerfiles atm so probably leave that until later

**Comment by Souheil-Yazji** [comment]
Added in https://github.com/StatCan/aaw-kubeflow-containers/pull/544/files#diff-339de570532e8f9ecebfc903347a13a20f902abd29f2ce259814fb1c7502faadR12
![Image](https://github.com/StatCan/aaw-kubeflow-containers/assets/35379392/214f764a-906c-4d67-977e-fcd1548bbea0)
