### ISSUE TITLE
Bug: Not able to install packages on Protected B Workspaces

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/aaw-kubeflow-containers#332]
I am unable to install packages from artifactory on Protected B notebook servers. I've tried waiting over an hour after creating the server and it still doesn't work.

```
> install.packages("tidyverse")
Warning in install.packages :
  unable to access index for repository https://jfrog.aaw.cloud.statcan.ca/artifactory/dev-cran-remote/src/contrib:
  cannot open URL 'https://jfrog.aaw.cloud.statcan.ca/artifactory/dev-cran-remote/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://jfrog.aaw.cloud.statcan.ca/artifactory/dev-cran-remote/src/contrib:
  cannot open URL 'https://jfrog.aaw.cloud.statcan.ca/artifactory/dev-cran-remote/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘tidyverse’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

I also tried `curl`

```
jovyan@prob-server-0:~$ curl https://jfrog.aaw.cloud.statcan.ca
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to jfrog.aaw.cloud.statcan.ca:443 
```

**Comment by bryanpaget** [comment]
This is still an issue. In order to install packages on the Protected B Notebook Servers, the user must specify the index-url, for instance to install opencv for Python:

```
pip install --index-url=http://jfrog-platform-artifactory-ha.jfrog-system:8081/artifactory/api/pypi/pypi-remote/simple --user opencv-python
```

**Comment by blairdrummond** [comment]
@vexingly this seems like an important issue to take a look at, and it's almost certainly networking related. Can you check? My guess is:

This is directing jfrog to the default gateway

https://github.com/StatCan/aaw-argocd-manifests/blob/bb1609479d234e5d4732d9f01850089cf471d6c3/kube-system/coredns-custom.jsonnet#L48

Maybe that's not allowed by network policies. Maybe we can either
1. Route this to a protected-b gateway?
2. Use Core-DNS to map this directly to the internal service location?

I'd also like @Jose-Matsuda 's opinion. In any case I think this is a regression, and one option is to just make the notebooks use the internal URL here, like we did before.

**Comment by Jose-Matsuda** [comment]
Yeah we can change back to internal URLs,  that will just mean notebooks on dev won't be able to use artifactory out of the box (but I think we're ok with this?). 

My understanding is limited, but what's involved in routing this to a protected b gateway, is it just changing to `protectedGateway` instead of `defaultGateway`? Are there any negatives to doing this / I guess if there is a notebook that is not protected b will it still be able to resolve? 

I do sorta like the Core-DNS-foo approach to map this to the internal service if we're in prod. 

Having said all that, maybe it would be better to have the internal URL be the default in our `aaw-kubeflow-containers` and then have the Core-DNS-foo do it for dev to make it obvious to the reader that all our containers look to an internal url.

**Comment by blairdrummond** [comment]
This might also be an option:

https://kubernetes.io/docs/concepts/services-networking/service/#externalname

An externalname service in Dev could point to `jfrog.aaw.cloud.statcan.ca` and that might solve the problem?

**Comment by blairdrummond** [comment]
Can I assign you @Jose-Matsuda  and you can decide a course-of-action?

**Comment by vexingly** [comment]
It's going to the regular ingressgateway for sure, but I'm not clear if that is failing because of that OR because of the network policies.

If we use minio as an example there are 2 network policies, one that specifies the ports and another (protected-b) that does not... Maybe we just need to add a new network policy that targets the artificatroy-ha pod without ports (or using 443) and see if that works with the default ingress gateway? (I don't have the ability to see what network polices exist in prod...).

If we just switch coredns to use the protected gateway then it will also be switched for non-protectedb pods, so like @Jose-Matsuda asked, will that work? We would need to have 2 separate url's to access artifactory for that solution so we can have 2 entries for coredns.

**Comment by Jose-Matsuda** [comment]
Closed via a merge into kubeflow-containers.

Still TODO
1) Update the configmap to use this (might want to wait juuust a bit)
2) Change the bulk-image update script to use whatever sha it is so when we do rescheduling on the weekend the protected b workloads also get this.
3) Decide on the course of action for dev / fixing this problem straight up, whether that be trying to use the _external name_ as suggested by Blair or something else.
