### ISSUE TITLE
jupyter/datascience-notebook base image pins Python to 3.9, causing conflicts with downgrade in jupyterlab-* images

### ISSUE THREAD

**Issue by ToucheSir** [StatCan/aaw-kubeflow-containers#344]
The pin: https://github.com/jupyter/docker-stacks/blob/4b830d5897d8f114009dab2945e8b339dba3cd78/base-notebook/Dockerfile#L117
The downgrade: https://github.com/StatCan/aaw-kubeflow-containers/blob/c5b7982c2054fe0e3962f7c128f260a7f7570cf5/output/jupyterlab-cpu/Dockerfile#L28

This is causing issues with Conda dependency resolution. Unfortunately the error is quite opaque, since I don't believe most users will be able to translate this:
```
Your pinning does not match what's currently installed. Please remove the pin and fix your installation
  Pin: python==3.9.7
  Currently installed: conda-forge/linux-64::python==3.8.12=hb7a2778_2_cpython
```
to "delete the line starting with `python` in `/opt/conda/conda-meta/pinned`".

**Comment by Jose-Matsuda** [comment]
I think one of the reasons we purposely downgraded was due to an incompatibility with the `ml-metadata` package as seen in the [comment](https://github.com/StatCan/aaw-kubeflow-containers/issues/305#issuecomment-996073700) right above this one. [ml-metadata](https://pypi.org/project/ml-metadata/) still seems to not _yet_ be available with 3.9 but maybe there does have to be a conversation regarding the importance of this package as I myself do not know how it is used. It might also actually contribute to https://github.com/StatCan/aaw-kubeflow-containers/issues/320 failing

**Comment by ToucheSir** [comment]
No qualms with the downgrade, but it seems that the pin file needs to go to unbreak Conda. I have to imagine this was added as part of a recent upgrade of the base image and not something on the StatCan side?

**Comment by Jose-Matsuda** [comment]
I'm imagining that your imagine is correct. That pin file was as you can see was added by upstream. I'm not too familiar with all this but truly if it is just the pin file that needs to go we can remove it on our side when we build our images.

Random info not too important but I went searching for it, 
We upgraded our [base image](https://github.com/StatCan/aaw-kubeflow-containers/blame/1b5c3b61281156b932506994d6c83e46ee32480d/output/jupyterlab-cpu/Dockerfile#L14) from this [older one](https://hub.docker.com/layers/base-notebook/jupyter/base-notebook/512afd49b925/images/sha256-60c1ee30573939b1290625d9ab91e362883c6a2ccd952cfaa6048595fca040e6?context=explore).

**Comment by ToucheSir** [comment]
That worked for me locally, but it may be too big of a hammer! Perhaps this is an isolated issue and other users haven't run into it?

**Comment by Souheil-Yazji** [comment]
Stale.
