### ISSUE TITLE
PyTorch and Tensorflow builds failing

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#345]
![image](https://user-images.githubusercontent.com/23174198/165943737-f00aac77-c3bf-4a7a-b3dd-a108bb32f2fc.png)

**Comment by brendangadd** [comment]
Looks like [the old key is added here](https://github.com/StatCan/aaw-kubeflow-containers/blob/d02880761eb2fef84ef27b682d5ca1e28d65e8cc/docker-bits/1_CUDA-11.1.Dockerfile#L12).

Should maybe update `CUDA_VERSION` while we're at it.

**Comment by Jose-Matsuda** [comment]
> Currently, there are 2 dockerfiles for CUDA. One is version 11.0.3 and the other is 11.2. Should both be updated to 11.7?

It might depend, if I look at the makefile [here](https://github.com/StatCan/aaw-kubeflow-containers/blob/a12fc131a871a6c660392fc83db4c5b3c4d5e703/Makefile#L16) there _might_ be a reason for the version difference?

**Comment by brendangadd** [comment]
@bsewp045 Great synopsis; thanks for the info.
* If/when your changes restore the image builds and produce working PyTorch and TF software, then this issue can be closed.
* I opened #361 for the further updates you mentioned. We can maybe pull it into next sprint.

I believe the difference in CUDA was simply due to Torch and TF requiring different versions at the time.

**Comment by bsewp045** [comment]
## Notes:

When creating a notebook server with the jupyterlab-pytorch image with gpu selected, you need to source the .bashrc file first before activating pytorch:

`source $HOME/.bashrc`
`conda activate torch`

To check if pytorch is actually using the gpu, run the following commands in a python script:
`import torch`
`torch.cuda.is_available()` - This should return true
`torch.cuda.device_count()` - This should return the number of gpus (1 in my case)
