### ISSUE TITLE
Update code-server French translation

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#387]
Some french content needs to be updated once https://github.com/StatCan/aaw-kubeflow-containers/pull/375 is merged in

i.e: 
![Image](https://user-images.githubusercontent.com/35379392/186431780-b2b7255c-3e3a-4e05-95fa-4bbecbbb7be1.png)

Extra information
https://github.com/StatCan/aaw-kubeflow-containers/pull/252#issuecomment-839912334

**Comment by Jose-Matsuda** [comment]
Note that oddly enough, on prod none of it is in French
![image](https://user-images.githubusercontent.com/23174198/188942959-4ecf6da8-e8c5-47aa-b5ee-6fe9ad2d362f.png)

**Comment by Jose-Matsuda** [comment]
Oh the reason for two installations is because we [turned off auto-update](https://github.com/StatCan/aaw-kubeflow-containers/commit/fb733f7d7e9ad50c661bf7201edd3e1441d50f0e#diff-596dcbf691a724a3ef6e54dd1ed336322e990684689eda03354f7a5425e31cfcL3), note that we had auto-update off [initially](https://github.com/StatCan/aaw-kubeflow-containers/pull/234)
