### ISSUE TITLE
Update our base docker images 

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-containers#423]
Almost a year to the date that we updated these last;
https://github.com/StatCan/aaw-kubeflow-containers/pull/307

Assigning size M as I'm sure there are at least a few incompatibilities that could arise and workarounds

Maybe also possibly update vs code for remote desktop image if it's not too much of a hassle

**Comment by mathis-marcotte** [comment]
For the remote desktop base image, I went with the rocker/geospatial:4.2.1 (https://hub.docker.com/layers/rocker/geospatial/4.2.1/images/sha256-5caca36b8962233f8636540b7c349d3f493f09e864b6e278cb46946ccf60d4d2?context=explore). There is a slightly newer version(4.2.2) but since that version, the image is built in ubuntu 22.04. This makes it so the python3 package installs python v3.10. But we have one dependency(ml-metadata) that isn't available

**Comment by mathis-marcotte** [comment]
I updated the cuda version for the tensorflow from 11.6 to 11.7, which is the same version as pytorch. This was because the base image is now on ubuntu 22.04. Cuda version 11.6 had a dependency to a package( `libcufile-11-6 : Depends: liburcu6 but it is not installable` ) that is not available for this version of Ubuntu, it was available on 20.04.
