### ISSUE TITLE
JupyterLab: Investigate disabled extensions

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#549]
Followup from https://github.com/StatCan/aaw-kubeflow-containers/issues/545

See the `Jupyterlab Extensions` section in this PR https://github.com/StatCan/aaw-kubeflow-containers/pull/544

After doing some digging with @Jose-Matsuda , it seems that some of those extensions aren't installed in our dockerfile, nor upstream. We'd have to do a little more digging as they could be dependencies which are outdated source-code wise.

**Comment by mathis-marcotte** [comment]
Not sure what is actually trying to install the `jupyterlab-git` extension, but I think I know why it's not enabled.
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/84033116/8426fd70-fd65-4359-bcc4-3e1e22f95a5b)

Our `JupyterLab` version is 4.0.7

**Comment by mathis-marcotte** [comment]
The extensions that are failing are all problems coming from the base image 
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/84033116/11b87004-e26f-4742-a196-060a200ee3b6)

The only one that isn't from upstream is `jupyterlab-plotly`

**Comment by mathis-marcotte** [comment]
Issue generally seems to be that these extensions don't work well will jupyterlab v4. Looking at these extensions that are getting disabled :
```
(base) jovyan@test-cpu-0:~$ jupyter labextension list
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2023-10-30 13:14:45.610 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v4.0.7
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyterlab-execute-time v3.0.1 enabled OK (python, jupyterlab_execute_time)
        jupyterlab-plotly v5.18.0 enabled  X
        nbdime-jupyterlab v2.2.0 enabled  X
        jupyter-matplotlib v0.11.3 enabled OK
        @jupyter-lsp/jupyterlab-lsp v5.0.0 enabled OK (python, jupyterlab-lsp)
        @jupyterhub/jupyter-server-proxy v4.0.0 enabled  X
        @jupyterlab/git v0.41.0 enabled  X (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.8 enabled OK (python, jupyterlab_widgets)

   The following extensions are outdated:
        jupyterlab_pygments
        jupyterlab-plotly
        nbdime-jupyterlab
        @jupyterhub/jupyter-server-proxy
        @jupyterlab/git
        
   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        jupyterlab-dash v0.4.2 enabled  X

   The following extensions are outdated:
        jupyterlab-dash
        
   Consider checking if an update is available for these packages.

Disabled extensions:
    @jupyterlab/completer-extension:base-service
    @jupyterlab/fileeditor-extension:language-server
    @jupyterlab/lsp-extension:settings
    @jupyterlab/notebook-extension:language-server
```

**Comment by mathis-marcotte** [comment]
Looking into downgrading jupyterlab version like [we used to](https://github.com/StatCan/aaw-kubeflow-containers/commit/23a315de708a6dc5cc48c5870f1b737b9a4cd803#diff-339de570532e8f9ecebfc903347a13a20f902abd29f2ce259814fb1c7502faadL8). 
But I honestly don't think that really worked since even testing with images that came before that commit, jupyterlab was a different version than the one specified (3.6.6 vs the 3.6.1 specified). 

I think that version difference mainly comes from either the jupyterlab-lsp or the jupyterlab_execute_time packages that have dependencies to a specific jupyterlab version. And we are [installing those packages](https://github.com/StatCan/aaw-kubeflow-containers/blob/23a315de708a6dc5cc48c5870f1b737b9a4cd803/docker-bits/6_jupyterlab.Dockerfile#L63C14-L63C14) after the jupyterlab version in the dockerfile. So one or both of those are overriding whatever version of jupyterlab we specified.

**Comment by mathis-marcotte** [comment]
Seems like the solution is to pin the version of `jupyterlab_execute_time` package to v2.3.1 (the most recent release of the previous major version). This makes it so jupyterlab gets the most recent v3 version(3.6.6) which also fixes all the extensions 
![image](https://github.com/StatCan/aaw-kubeflow-containers/assets/84033116/3968f0d0-b360-4ca2-84cd-77270209f2ef)
