### ISSUE TITLE
Docker: Investigate R package mamba install failing

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/aaw-kubeflow-containers#684]
The following mamba install command fails to resolve 
https://github.com/StatCan/aaw-kubeflow-containers/blob/master/docker-bits/6_rstudio.Dockerfile#L13-L27

### Possible approaches to debug
- Execute the mamba install command on a local image (will need to point to an upstream channel)
- Execute the mamba install command on an LVM 
- Remove the quiet flag and build the image (less efficient)
- dissolve the command into isolated mamba install calls

**Comment by AbdallaAbdelhadi** [comment]
### @Souheil-Yazji Here is what I found out:
- First I tried installing all the packages independently to check weather maybe one package takes longer than the others but all them seemed to download around the same time
- Then I started to increase the amount of packages installed in a single command. I noticed that as you increase the packages mamba takes longer to download. And at round like 6-7 packages it just gets stuck searching for the packages and never downloads. Seems like mamba has a problem of resolving lots of packages together in one command.

### Possible solutions:
- First solution I tried is breaking down the download command. As I mentioned the more packages we install in one command the longer it takes, so the more we break it down the better the execution.
- Second solution I tried is using conda instead of mamba. This took <5min to download all the packages.
- Third solution I tried is upgrading mamba to version 2.0.0 (the version being ran in the image is 1.5.8). This solution executed a little better than using conda.

**Comment by Souheil-Yazji** [comment]
Thank you for investigating!
